# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HW 26 Topchii Roman iOS 19-2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HW 26 Topchii Roman iOS 19-2
    pod 'PKHUD', '~> 5.0'
end
